development:
  forest_env_secret: bf1aff6ed276c9d0dd8a8bcc49b143780c6f2db433a17233abc31797fc6835b1
  forest_auth_secret: tY4oDMV0VfltKts7lj0U8Q
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
